import type { CollectionItem } from '../dashboard/types'

export const museumCollectionItems: CollectionItem[] = [
  {
    id: 'min-fang-lei',
    modelUrl: '/models/collection/314d93528e137d58dca42f12f2ecc947.fbx',
    name: '皿方罍',
    meta: '商晚期 | 青铜礼器',
    summary: '以兽面纹与高浮雕棱脊见长，是馆藏青铜器中的代表性重器。',
    badge: '青铜重器',
    period: '商代晚期',
    material: '青铜',
    origin: '湖南宁乡黄材',
    hall: '青铜艺术专题展厅',
    size: '通高63.6cm',
    description: [
      '皿方罍器形雄浑，腹部鼓张，四面转角起棱，整体比例挺拔而稳定，是中国青铜文明中极具识别度的礼器类型。',
      '器身通体装饰兽面纹、夔龙纹与云雷纹，层级清晰，既体现出商代晚期高超的范铸技艺，也展示了礼制器物在权力表达中的象征意义。',
    ],
    highlights: ['四角棱脊与高浮雕耳部特征明显', '纹饰层次复杂，适合做三维细节观察', '是湖南地域青铜文化叙事中的核心馆藏'],
  },
  {
    id: 'renwu-yulong-bohua',
    modelUrl: '/models/collection/224fabdf387ccb40aabd5572c20fc3f4.fbx',
    name: '人物御龙帛画',
    meta: '战国 | 帛画',
    summary: '以极简线描表现升腾意象，是研究楚地丧葬与信仰的重要图像材料。',
    badge: '楚地帛画',
    period: '战国中晚期',
    material: '丝织物设色',
    origin: '湖南长沙子弹库楚墓',
    hall: '楚文化专题展厅',
    size: '纵37.5cm，横28cm',
    description: [
      '人物御龙帛画采用极其克制的线描方式刻画人物与龙凤形象，构图精炼，却保留了强烈的升腾感与宗教想象。',
      '它不仅是战国绘画史上的关键实物，也为理解楚地丧葬仪式、灵魂观念和图像叙事方式提供了直接证据。',
    ],
    highlights: ['线描极简但动态强烈', '图像叙事与楚地信仰关系紧密', '脆弱材质适合数字化展示与放大解读'],
  },
  {
    id: 'changsha-kiln-pot',
    modelUrl: '/models/collection/base_basic_pbr.glb',
    name: '长沙窑青釉褐彩执壶',
    meta: '唐代 | 陶瓷',
    summary: '釉彩对比鲜明，体现了长沙窑面向民间与外销市场的成熟工艺。',
    badge: '长沙窑',
    period: '唐代',
    material: '瓷胎青釉褐彩',
    origin: '长沙铜官窑遗址',
    hall: '陶瓷工艺展厅',
    size: '通高27cm',
    description: [
      '长沙窑青釉褐彩执壶兼具实用性与装饰性，器身饱满，流、柄与腹部过渡流畅，是唐代日用瓷中非常成熟的器型。',
      '褐彩在青釉背景上形成鲜明对比，体现出长沙窑对彩绘装饰和市场审美的敏锐把握，也反映了外销瓷传播中的地域特征。',
    ],
    highlights: ['适合观察釉色层次与器型转折', '表现出民窑市场导向的审美语言', '可用于讲述海上贸易与外销瓷故事'],
  },
  {
    id: 'xiangxiu-screen',
    modelUrl: '/models/collection/0ce3ed5e3f9c51f96337b474e6294df1.glb',
    name: '湘绣花鸟屏',
    meta: '清代 | 刺绣',
    summary: '以丝线层次与设色过渡取胜，能直观看到湖南地方工艺的审美取向。',
    badge: '湘绣精品',
    period: '清代',
    material: '丝线、绢地',
    origin: '湖南地区旧藏',
    hall: '非遗工艺展厅',
    size: '屏心高112cm',
    description: [
      '湘绣花鸟屏通过丝线粗细、针法方向与设色深浅的变化，形成接近绘画的明暗关系与羽毛质感，是湖南刺绣工艺成熟阶段的代表作品。',
      '在展示中，这类作品非常适合与放大细节、工艺流程和地域审美叙事结合，用来解释传统手工艺如何在近距离观察中建立价值感。',
    ],
    highlights: ['针法与设色细节丰富', '适合做工艺解说型数字展示', '能与地方非遗叙事形成联动'],
  },
]
